"""empty message

Revision ID: 895f7e0eebfe
Revises: 7cd85f9be251
Create Date: 2022-11-22 19:00:46.348625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895f7e0eebfe'
down_revision = '7cd85f9be251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todolists', schema=None) as batch_op:
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todolists', schema=None) as batch_op:
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
